"use strict";

GSUI.setTemplate( "gsui-slicer", () => ( [
	GSUI.createElement( "div", { class: "gsuiSlicer-source" },
		GSUI.createElement( "div", { class: "gsuiSlicer-source-head" },
			GSUI.createElement( "i", { class: "gsuiSlicer-source-icon gsuiIcon", "data-icon": "waveform" } ),
			GSUI.createElement( "span", { class: "gsuiSlicer-source-name" } ),
		),
		GSUI.createElement( "div", { class: "gsuiSlicer-source-sample-wrap" },
			GSUI.createElement( "div", { class: "gsuiSlicer-source-sample" },
				GSUI.createElementSVG( "svg", { class: "gsuiSlicer-source-wave", viewBox: "0 0 1000 64", preserveAspectRatio: "none" },
					GSUI.createElementSVG( "polyline" ),
				),
				GSUI.createElement( "div", { class: "gsuiSlicer-currentTime gsuiSlicer-source-currentTime" } ),
			),
		),
	),
	GSUI.createElement( "div", { class: "gsuiSlicer-time" },
		GSUI.createElement( "gsui-timeline" ),
	),
	GSUI.createElement( "div", { class: "gsuiSlicer-preview" },
		GSUI.createElement( "div", { class: "gsuiSlicer-currentTime gsuiSlicer-preview-currentTime" } ),
	),
	GSUI.createElement( "div", { class: "gsuiSlicer-slices" },
		GSUI.createElement( "div", { class: "gsuiSlicer-slices-scroll" },
			GSUI.createElement( "div", { class: "gsuiSlicer-slices-in" },
				GSUI.createElement( "div", { class: "gsuiSlicer-slices-beatlinesWrap" },
					GSUI.createElement( "gsui-beatlines" ),
					GSUI.createElement( "gsui-beatlines", { vertical: true } ),
				),
				GSUI.createElement( "div", { class: "gsuiSlicer-currentTime gsuiSlicer-slices-currentTime" } ),
				GSUI.createElementSVG( "svg", { class: "gsuiSlicer-slices-line", preserveAspectRatio: "none" },
					GSUI.createElementSVG( "line" ),
				),
				GSUI.createElement( "div", { class: "gsuiSlicer-slices-wrap" } ),
			),
		),
	),
	GSUI.createElement( "div", { class: "gsuiSlicer-menu" },
		GSUI.createElement( "button", { class: "gsuiSlicer-btn gsuiSlicer-btn-step", title: "Магнит" },
			GSUI.createElement( "span", { class: "gsuiSlicer-btn-step-value" } ),
			GSUI.createElement( "i", { class: "gsuiIcon", "data-icon": "magnet" } ),
		),
		GSUI.createElement( "button", { class: "gsuiSlicer-btn gsuiIcon", "data-action": "moveY", "data-icon": "hand-pointer", title: "Сдвинуть слайсы вертикально" } ),
		GSUI.createElement( "button", { class: "gsuiSlicer-btn gsuiIcon", "data-action": "reset", "data-icon": "slices", title: "Отменить сдвиг" } ),
		GSUI.createElement( "button", { class: "gsuiSlicer-btn gsuiIcon", "data-action": "split", "data-icon": "cut", title: "Разрезать слайсы пополам" } ),
		GSUI.createElement( "button", { class: "gsuiSlicer-btn gsuiIcon", "data-action": "merge", "data-icon": "erase", title: "Перемешать слайсы" } ),
	),
] ) );
