"use strict";

GSUI.setTemplate( "gsui-daw-popup-settings", () => (
	GSUI.createElement( "div", { class: "gsuiDAW-popup-settings" },
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Аудио" ),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Частота дискретизации" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "select", { name: "sampleRate" },
						GSUI.createElement( "option", { value: 8000 }, "8 kHz" ),
						GSUI.createElement( "option", { value: 11025 }, "11.025 kHz" ),
						GSUI.createElement( "option", { value: 12000 }, "12 kHz" ),
						GSUI.createElement( "option", { value: 22050 }, "22.05 kHz" ),
						GSUI.createElement( "option", { value: 24000 }, "24 kHz" ),
						GSUI.createElement( "option", { value: 44100 }, "44.1 kHz" ),
						GSUI.createElement( "option", { value: 48000, style: "font-weight:bold" }, "48 kHz" ),
						GSUI.createElement( "option", { value: 88200 }, "88.2 kHz" ),
						GSUI.createElement( "option", { value: 96000 }, "96 kHz" ),
					),
				),
			),
		),
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Частота обновления пользовательского интерфейса" ),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Автоматически" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "label", null,
						GSUI.createElement( "input", { name: "uiRate", type: "radio", value: "auto" } ),
						GSUI.createElement( "span", { class: "gsuiDAW-uiRateFps" }, 60 ),
					),
				),
			),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Ручной режим" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "label", null,
						GSUI.createElement( "input", { name: "uiRate", type: "radio", value: "manual" } ),
						GSUI.createElement( "span", { class: "gsuiDAW-uiRateFps" }, 40 ),
					),
					GSUI.createElement( "input", { name: "uiRateFPS", type: "range", step: 1, min: 5, max: 40, value: 40 } ),
				),
			),
		),
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Окна" ),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Режим перемещения/изменения размера" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "label", null,
						GSUI.createElement( "input", { name: "windowsLowGraphics", type: "checkbox" } ),
						GSUI.createElement( "span", null, "Упрощенный" ),
					),
				),
			),
		),
		GSUI.createElement( "fieldset", null,
			GSUI.createElement( "legend", null, "Таймлайн" ),
			GSUI.createElement( "div", { class: "gsuiPopup-row" },
				GSUI.createElement( "div", { class: "gsuiPopup-row-title" }, "Нумерация с" ),
				GSUI.createElement( "div", { class: "gsuiPopup-row-values" },
					GSUI.createElement( "select", { name: "timelineNumbering" },
						GSUI.createElement( "option", { value: 0 }, 0 ),
						GSUI.createElement( "option", { value: 1 }, 1 ),
					),
				),
			),
		),
	)
) );
